### ISSUE TITLE
Support for CSS Background images

### ISSUE THREAD

**Issue by Maingron** [Maingron/imageFormatFallback.js#3]
It might be possible to add support for CSS Background images.
Maybe the programmers CSS could then look something like this:
```CSS
body {
     background-image:url("/img/background.webp");
     background-image-formats: webp, png, jpg;
}
```

I'm not sure if it's possible to access the CSS's "background-image-formats" through Javascript and I'm also not sure how reliable this would work, but it's worth a try!
